export const SET_VISITORS = "SET_VISITORS";
export const SET_VISITORS_ERROR = "SET_VISITORS_ERROR";
export const SET_VISITORS_MESSAGE = "SET_VISITORS_MESSAGE";
export const SET_VISITORS_LOADING = "SET_VISITORS_LOADING";
